server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/rating-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka